---
title: "Backward design for data science curricula, courses, and course assignments"
author:
  - Frederick J. Boehm:
      email: frederick.boehm@gmail.com
      institute: [UMMS]
      correspondence: true
  - Bret M. Hanlon:
      email: bmhanlon@wisc.edu
      institute: [UW]
      correspondence: false
institute:
  - UMMS: University of Massachusetts Medical School
  - UW: University of Wisconsin-Madison
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    bookdown::html_document2:
      fig_caption: yes
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
    bookdown::pdf_document2:
      fig_caption: yes
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua  
    bookdown::word_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
bibliography: references.bib
link-citations: true
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Backward design  
keywords: |
  Backward design; data science
highlights: |
  These are the highlights. 
---


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 300
)
```

# Introduction


# Background



# Methods


# Results

# Discussion



# Conclusion



# Acknowledgements


<!-- The following line inserts a page break  -->
\newpage

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

\newpage

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```


